apiVersion: v1
kind: Pod
metadata:
  labels:
    run: buxybox
  name: buxybox
spec:
  containers:
  - image: busybox
    name: buxybox
    command: ["/bin/sh", "-c", "sleep 3600"]
  restartPolicy: Never
