apiVersion: v1
kind: Pod
metadata:
  labels:
    run: fruit-service
  name: fruit-service
spec:
  containers:
  - name: haproxy
    image: haproxy:1.7
    ports:
      - containerPort: 80
    volumeMounts:
      - name: config-volume
        mountPath: /usr/local/etc/haproxy

  - name: fruit-service
#    image: busybox
    image: linuxacademycontent/legacy-fruit-service:1
  volumes:
    - name: config-volume
      configMap:
        name: fruit-service-ambassador-config
  restartPolicy: Never
