# kubectl create job busybox --image busybox -- /bin/sh -c "echo Hello World && sleep 5" > job.yaml
apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: null
  name: busybox
spec:
  completions: 5
  parallelism: 2
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - command:
        - /bin/sh
        - -c
        - echo Hello World && sleep 10
        image: busybox
        name: busybox
        resources: {}
      restartPolicy: Never
status: {}
