version: '3'

services:
  drupal:
    image: drupal:8-apache
    ports:
      - 8080:80
    volumes:
      - /var/www/html/modules
      - /var/www/html/profiles
      - /var/www/html/themes
      - /var/www/html/sites
    restart: always
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: pass123
    volumes:
      - my_db:/var/lib/postgresql/data

volumes:
  my_db: