version: '3.4'
services:
    redis:
        image: redis:alpine
        networks:
            - frontend
        deploy:
            replicas: 1
            update_config:
              failure_action: rollback
    db:
        image: postgres:9.6
        volumes:
            - db-data:/var/lib/postgresql/data
        networks:
            - backend
        deploy:
            replicas: 1
            update_config:
              failure_action: rollback
    vote:
        image: bretfisher/examplevotingapp_vote
        ports:
            - '80:80'
        networks:
            - frontend
        depends_on:
            - redis
        deploy:
            replicas: 2
            update_config:
                failure_action: rollback
                order: start-first
    result:
        image: bretfisher/examplevotingapp_result
        ports:
            - '5001:80'
        networks:
            - backend
        depends_on:
            - db
            - redis
        deploy:
            replicas: 1

    worker:
        image: bretfisher/examplevotingapp_worker:java
        networks:
            - frontend
            - backend
        depends_on:
            - db
            - redis
        deploy:
            replicas: 2

networks:
    frontend:
    backend:

volumes:
    db-data:

