apiVersion: v1
kind: ReplicationController
metadata:
  annotations:
    kubernetes.io/change-cause: kubectl run kubia --image=andreistefanciprian/kubia
      --port=8080 --generator=run/v1 --record=true --dry-run=true --output=yaml
#  labels:
#    run: kubia
  name: kubia
spec:
  replicas: 3
  selector:
    run: kubia
  template:
    metadata:
      labels:
        run: kubia
    spec:
      containers:
      - image: andreistefanciprian/kubia
        imagePullPolicy: IfNotPresent
        name: kubia
        ports:
        - containerPort: 8080
