apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  annotations:
    kubernetes.io/change-cause: kubectl autoscale deployment nginx --min=1 --max=5
      --cpu-percent=60 --dry-run=true --output=yaml --record=true
  creationTimestamp: null
  name: nginx
spec:
  maxReplicas: 5
  minReplicas: 1
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: nginx
  targetCPUUtilizationPercentage: 60
status:
  currentReplicas: 0
  desiredReplicas: 0
