apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx
  name: nginx
spec:
  containers:
  - image: nginx
    name: nginx
    args:
      - /bin/sh
      - -c
      - sleep 30; rm -rf /usr/share/nginx/html/index.html; sleep 600
    livenessProbe:
      httpGet:
        path: /index.html
        port: 80
      periodSeconds: 5
      initialDelaySeconds: 5

  restartPolicy: OnFailure

