apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubernetes.io/change-cause: kubectl run busybox /bin/sh -c while true; do wget
      -q -O- http://task-pv-pod/; sleep 5; done --image=busybox --restart=Never --record=true
      --dry-run=true --output=yaml

  labels:
    run: busybox
  name: busybox
spec:
  containers:
  - args:
    - /bin/sh
    - -c
    - while true; do wget -q -O- http://task-pv-pod/; sleep 5; done
    image: busybox
    name: busybox
    resources: {}

  restartPolicy: Never

