apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubernetes.io/change-cause: kubectl run busybox /bin/sh -c sleep 3600 --image=busybox
      --restart=Never --record=true --dry-run=true --output=yaml
  creationTimestamp: null
  labels:
    run: busybox
  name: busybox
spec:
#  nodeSelector:
#    gpu: "false"
  containers:
  - args:
    - /bin/sh
    - -c
    - sleep 3600
    image: busybox
    imagePullPolicy: IfNotPresent
    name: busybox
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
